### ISSUE TITLE
Civ destroyed not displayed until end of turn

### ISSUE THREAD

**Issue by axx0** [fire-eggs/CivOne#108]
It should be displayed immediately after you destroy last enemy city.
The check currently happens at EndTurn() method in Game.cs.

**Comment by fire-eggs** [comment]
You're going to have to be more specific: in what exact scenario does this occur? 

There are six places where the `IsDestroyed()` check is made. Easily could be missing one.

In general, the message appears immediately - there was one place missing from SWY's code, see issue #55.

**Comment by kazgaroth011** [comment]
Started up a normal game, not too long into the game I conquer an enemy city (only one it had) and as you've said the message should appear immediately, but it doesn't, it appears at the end of turn.

**Comment by fire-eggs** [comment]
Thanks - need to hunt for another city conquest scenario then.

**Comment by fire-eggs** [comment]
Can't repro. The "civ destroyed" message will appear at the end of the turn if the unit doing the capturing is the last one during the turn.
