### ISSUE TITLE
Clicking in view map interrupts Goto destination selection

### ISSUE THREAD

**Issue by fire-eggs** [fire-eggs/CivOne#12]
In Microprose, you can click on the inner map to move the viewpoint during a Goto destination selection. This way the destination is visible.

In current CivOne, the Goto is interrupted by clicking in the inner map.

**Comment by fire-eggs** [comment]
The implementation in Goto.cs "just seems wrong". Goto.cs is a screen, and ignores/escapes when the user clicks in the minimap.  Since it is a screen, it doesn't seem to be possible to change the game view (GamePlay.X, GamePlay.Y).

I believe the "correct" implementation is a "mode" in GamePlay.cs. When in 'Goto' mode, switch the cursor to 'Goto', and allow minimap click to move the GameView.

**Comment by iegik** [comment]
I've implemented "just work" case for minimap
