### ISSUE TITLE
GoTo: Cannot open City View when no waiting units available

### ISSUE THREAD

**Issue by iegik** [fire-eggs/CivOne#148]
When you send last active unit to some GoTo target, your turn automatically ends and not able to select any city or unit until all units with GoTo order completes its path or faced with problem (enemy attack or unable to move to enemies territory)

In Microprose release, you must manually end each turn after all auto-units complete its turn.

How to reproduce:
- Build a city
- Build a unit
- Send unit to far far away
Now you can see that you are enable to do something and your turns immediately ends one by one while the only unit goes to the target.

**Comment by fire-eggs** [comment]
Nice catch!

**Comment by iegik** [comment]
I think that was in my local branch. Cannot reproduce now :(
