### ISSUE TITLE
Pillage will clear the roads too

### ISSUE THREAD

**Issue by iegik** [fire-eggs/CivOne#154]
In original, clears only Irrigation, pollution and if I'm correct - mines, but not roads!
Related with https://github.com/fire-eggs/CivOne/pull/141

**Comment by fire-eggs** [comment]
This is a little subtle.
Barbarians do not pillage roads: only irrigation or mines.

The AI civilizations and the human can pillage, and in this order:
- railroad
- irrigation / mine
- road

As per the CIV manual.

**Comment by iegik** [comment]
Ok
