### ISSUE TITLE
Pilling not work on swamp

### ISSUE THREAD

**Issue by iegik** [fire-eggs/CivOne#155]

**Comment by fire-eggs** [comment]
Not sure what you're saying here.

If I create an improvement (e.g. a road) on a swamp tile, then Pillaging is possible and removes the road.

**Comment by iegik** [comment]
<img width="639" alt="Screenshot 2021-11-08 at 19 22 54" src="https://user-images.githubusercontent.com/175293/140779575-559323c6-3179-4722-9e75-091a178093de.png">
Can reproduce.
In original, you can press 'P' (Pillage) on swamp tile and it will be converting to the forest with horse.

**Comment by fire-eggs** [comment]
You'll have to remind me which version of "original CIV" you're running. I
just tried it in the .02 version and nothing happens [the settler's turn is
ended but nothing happens to the landscape].


On Mon, Nov 8, 2021 at 11:25 AM Arturs Jansons ***@***.***>
wrote:

Can reproduce. In original, you can press 'P' (Pillage) on swamp tile and
> it will be converting to the forest with horse.
