### ISSUE TITLE
Units are being allowed to move into places they shouldn't

### ISSUE THREAD

**Issue by fire-eggs** [fire-eggs/CivOne#93]
Need to review the "move not allowed" logic. Compare vs the Civ Manual, page 98.

**Comment by fire-eggs** [comment]
Confirmed. In this scenario:
![image](https://user-images.githubusercontent.com/9809727/62973455-15f3c080-bde4-11e9-95c8-60ae9f59102f.png)

the legion is not permitted to move up-and-left to the city [Microprose].

However, in CivOne, that move is allowed.

See BaseUnit.cs, `MoveTo`, the if statement which starts:
`if (Class == UnitClass.Land && !(this is Diplomat || this is Caravan)`

**Comment by kazgaroth011** [comment]
This was an open issue in CivONE and I believe SWY corrected this, but the problem seems to have resurfaced.

**Comment by fire-eggs** [comment]
Ah! Thanks for the tip!

The current logic is quite close but fails to check for an _enemy city's_ zone-of-control.

**Comment by fire-eggs** [comment]
fixed.

**Comment by fire-eggs** [comment]
Now have broken two things.
1. Should be able to move to a location which has friendly units.
2. Need to confirm: can move into undefended city, even if sorta blocked by enemy unit?

**Comment by fire-eggs** [comment]
Fixed broken stuff.
